### ISSUE TITLE
Review

### ISSUE THREAD

**Issue by daida** [mackoj/SimulatorControl#13]
// MARK

https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/CommandParser/Command.swift#L4

failable init ?
https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/CommandParser/Command.swift#L10

Convinient init ?
https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/Platform.swift#L13

Remove (it) -> Bool utilise juste it in

https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/PlatformLookup%2BDeviceFamily.swift#L20

guard ?

https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/PlatformLookup%2BDeviceFamily.swift#L23

Je sais qu'on faisait ca MSTV, mais je suis plus très fan du fait que ta key soit la valeur EN de ta LocaliseString, je préfère des truc en error.invalid_index

https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/PlatformLookup%2BError.swift#L18

pourquoi optionnel ?

https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/PlatformLookup%2BError.swift#L47

typedef de tes closures de retours

https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/PlatformLookup%2BFilters.swift#L11

last! -> pas beau je sais ca casse le style du one liner... mais c'est la vie..

https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/PlatformLookup%2BFindDevices.swift#L87

Pas besoin d'explicit (runtime) -> Platform?

https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/PlatformLookup%2BFindDevices.swift#L102

isEmpty == false

https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/PlatformLookup%2BFindDevices.swift#L105

Il faut récupérer cette variable de quelque part je pense.. env, secret je sais pas mais je sais pas si c'est cool d'assumer bash

https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/Shell/Shell.swift#L21

**Comment by daida** [comment]
Le commentaire fait référence au link en dessus ou en dessous je me suis planté a moment donné de la review, mais c'est

**Comment by daida** [comment]
C'est pas mal du tout, ca manque de // MARK de doc et d'aération dans la mise en page (c'est peut être swiftFormat)

Passe un coup de swiftlint dessus si tu peux.

Sinon 👍

**Comment by mackoj** [comment]
@daida Merci pour la relecture ! En general je préfère avoir les types définie ci possible si a terme cela devient une mauvaise pratique swift-lint/swift-format me les supprimeront. Sinon pour le reste merci ! 🙏 

Si je veux gérer correctement les erreurs il me faut des `throws` et l'avantage est que j'ai moins d'optionnel dans le code.

> failable init ?
> 
> https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/CommandParser/Command.swift#L10

Bien vue !
> Convinient init ?
> 
> https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/Platform.swift#L13

Pour l'instant je ne peux pas simplement faire des lib avec ressources mais cela ne saurait tarder des que c'est le cas je migre 👍 https://github.com/apple/swift-evolution/blob/master/proposals/0271-package-manager-resources.md
> Je sais qu'on faisait ca MSTV, mais je suis plus très fan du fait que ta key soit la valeur EN de ta LocaliseString, je préfère des truc en error.invalid_index
> 
> https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/PlatformLookup%2BError.swift#L18

C'est comme cela que l'api de `LocalizedError` fonctionne.
> pourquoi optionnel ?
> 
> https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/PlatformLookup%2BError.swift#L47

J'ai forcement au moins un résultat sinon sa throw un peu plus tot ! Il me faudrait un type style non empty array pour fixer cela mieux mais je t'avoue que je n'ai pas envie d'avoir trop de lib https://github.com/pointfreeco/swift-nonempty 
> last! -> pas beau je sais ca casse le style du one liner... mais c'est la vie..
> 
> https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/PlatformLookup/PlatformLookup%2BFindDevices.swift#L87

Tu a complemetement raison mais je ne sais pas comment le faire deplus ce tool ne va tourner que sur OSX
> Il faut récupérer cette variable de quelque part je pense.. env, secret je sais pas mais je sais pas si c'est cool d'assumer bash
> 
> https://github.com/mackoj/SimulatorControl/blob/8c3b14ff2eb79202d451b6a28970ec1e1db7af4e/Sources/Shell/Shell.swift#L21

**Comment by mackoj** [comment]
Au final j'ai rajouter nonempty
